[language-server.typescript-language-server]
command = "tsc"
args = ["--lsp", "--stdio"]

[language-server.oxfmt]
command = "oxfmt"
args = ["--lsp"]


[[language]]
name = "typescript"
language-servers= [{ name = "oxfmt", only-features = [ "format" ] }, "typescript-language-server"]
auto-format = true

[[language]]
name = "tsx"
language-servers= [{ name = "oxfmt", only-features = [ "format" ] }, "typescript-language-server"]
auto-format = true

[[language]]
name = "javascript"
language-servers= [{ name = "oxfmt", only-features = [ "format" ] }, "typescript-language-server"]
auto-format = true

[[language]]
name = "jsx"
language-servers= [{ name = "oxfmt", only-features = [ "format" ] }, "typescript-language-server"]
auto-format = true
