# theme = "monokai_pro"
theme = "onedark_transparent"

[editor]
mouse = true

scrolloff = 5
line-number = "relative"
bufferline = "multiple"
cursorline = true

auto-format = true
end-of-line-diagnostics = "hint"

# rulers = [80, 120]
trim-final-newlines = true
trim-trailing-whitespace = true

[editor.lsp]
auto-signature-help = false

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
normal = "underline"
insert = "bar"


[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]

# Vim binds
C-e = "scroll_down"
C-y = "scroll_up"
