# Alacritty configuration written in TOML

# General
live_config_reload = true
ipc_socket = true

[window]
opacity = 0.95
blur = true
dynamic_title = true

[font]
normal = { family = "Iosevka Term" }
size = 17.5
